### PR TITLE
Fix/fix error 201711

### PR DESCRIPTION
**Pull request by yumetodo**
- fix compiler warnings in Clang CodeGen
- Support msys2 mingw gcc

### CODE REVIEW

**Review by benikabocha — CHANGES_REQUESTED** [review]
Erasing the wrong function.
IsU16HighSurrogate() is used.

**Comment by yumetodo** [comment]
@benikabocha Oh... I should had removed `IsU32Surrogate`, not `IsU16HighSurrogate`.

**Review by benikabocha — APPROVED** [review]

**Comment by benikabocha** [comment]
Could you please merge the new code?

**Comment by yumetodo** [comment]
@benikabocha hmm...

```sh
$git fetch --all
Fetching origin
Fetching upstream
$git merge upstream/master
Already up-to-date.
$git status
On branch fix/fix_error_201711
Your branch is up-to-date with 'origin/fix/fix_error_201711'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .vscode/

nothing added to commit but untracked files present (use "git add" to track)
```

I don't know why github shows `This branch has conflicts that must be resolved`...

**Comment by akinomyoga** [comment]
That's weird... Maybe you could try to recreate the merge commit.

```sh
# on the branch fix/fix_error_201711

$ git reset --hard cce9880
$ git merge upstream/master
$ git push -f
```

**Comment by yumetodo** [comment]
@akinomyoga Thank you!

@benikabocha Could you merge this?

**Comment by benikabocha** [comment]
@yumetodo @akinomyoga  Thank you!

**Pull request merged**
